//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class competitor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public competitor()
        {
            this.games = new HashSet<game>();
        }
    
        public int Competitor_ID { get; set; }
        public string Competitor_Salutation { get; set; }
        public string Competitor_Name { get; set; }
        public System.DateTime Competitor_DoB { get; set; }
        public string Competitor_Email { get; set; }
        public string Competitor_Description { get; set; }
        public string Competitor_Country { get; set; }
        public bool Competitor_Gender { get; set; }
        public int Competitor_ContactNo { get; set; }
        public string Competitor_Website { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<game> games { get; set; }
    }
}
