//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventcompetitorresult
    {
        public int Event_ID { get; set; }
        public int Competitor_ID { get; set; }
        public string Competitor_Position { get; set; }
        public string Competitor_Medal { get; set; }
    }
}
