//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int Event_ID { get; set; }
        public int Game_ID { get; set; }
        public string FeatureEvent { get; set; }
        public string EventVenu { get; set; }
        public System.DateTime EventDate { get; set; }
        public System.TimeSpan EventStartTime { get; set; }
        public System.TimeSpan EventEndTime { get; set; }
        public string EventDescription { get; set; }
        public System.TimeSpan WorldRecord { get; set; }
    }
}
