//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public int userId { get; set; }
        public string userEmail { get; set; }
        public string userPassword { get; set; }
        public bool userType { get; set; }
    }
}
