//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sportsmanagementEntities : DbContext
    {
        public sportsmanagementEntities()
            : base("name=sportsmanagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<competitor> competitors { get; set; }
        public virtual DbSet<eventcompetitorresult> eventcompetitorresults { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<game> games { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<posteventinfo> posteventinfoes { get; set; }

		public System.Data.Entity.DbSet<SportsManagement.Models.ViewModel.UserLoginView> UserLoginViews { get; set; }
	}
}
