//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class posteventinfo
    {
        public int Photo_ID { get; set; }
        public byte[] Event_Photo { get; set; }
        public string Event_PhotoTags { get; set; }
        public int Event_ID { get; set; }
    }
}
